FROM node:14-alpine
LABEL Author Simone Boscolo Berto <simone.boscoloberto@protonmail.com>

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app
RUN npm install

EXPOSE 3000

CMD [ "npm", "start" ]
