swagger: "2.0"
info:
  version: 1.0.0
  title: blog
  description: Simple Blog Application
basePath: /api/v1
tags:
  - name: Posts
    description: Posts endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  PostBody:
    type: object
    title: post
    required:
      - title
      - body
    properties:
      title:
        type: string
        title: post n.1
      body:
        type: string
        body: Lorem Ipsum lorem ipsum..
      comments:
        type: integer
        comments: 3

paths:
  /posts:
    get:
      tags:
        - Posts
      description: Fetch all posts
      responses:
        200:
          description: Returns all posts
    post:
      tags:
        - Posts
      description: Create a new Post
      parameters:
        - name: post
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/PostBody"
      responses:
        200:
          description: Returns all examples

  /posts/{id}:
    get:
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Post to retrieve
          type: integer
      responses:
        200:
          description: Return the Post with the specified id
        404:
          description: Post not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification